### ISSUE TITLE
[proposta] Arquitetura de um projeto Flask

### ISSUE THREAD

**Issue by rochacbruno** [pyjamasconf/pyjamas-conf-2019#13]
```yaml
titulo: Arquitetura de um Projeto Flask
palestrantes:
  - nome: Bruno Rocha
  - link: http://twitter.com/rochacbruno
  - url: https://avatars0.githubusercontent.com/u/458654?s=400&v=4
publico: intermediário
descricao: >
  Live-code mostrando como organizar a estrutura de arquivos de um 
  Projeto Flask, como instalar extensões, blueprints, como criar apps 
  reusáveis e boas práticas.
tags:
  - flask
  - web
  - arquitetura
  - framework
formato: live-code
duracao: 60
inicio: 2019-12-13 17:30:00
url: https://youtu.be/6mhTm6Luyhk
```
